<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../../api/client'
import DynamicQuestion from '../../components/DynamicQuestion.vue'
import { createIdempotencyKey } from '../../utils/idempotency'

const route=useRoute();const accessCode=ref('123456');const verified=ref(false);const loading=ref(false);const packageData=ref<any>();const current=ref<any>();const answers=ref<Record<string,any>>({});const revision=ref(0);const saveState=ref('已保存');const submitted=ref(false);let timer:number|undefined
const visibleQuestions=computed(()=>{if(!current.value)return[];return current.value.schema.sections.flatMap((s:any)=>s.questions.map((q:any)=>({...q,sectionTitle:s.title}))).filter((q:any)=>!q.show_if||answers.value[q.show_if.question_key]===q.show_if.equals)})
async function verify(){loading.value=true;try{const {data}=await api.post('/patient-session/verify',{token:route.params.token,access_code:accessCode.value});sessionStorage.setItem('patient_token',data.access_token);verified.value=true;await loadTasks()}catch(e){ElMessage.error((e as Error).message)}finally{loading.value=false}}
async function loadTasks(){packageData.value=(await api.get('/patient-session/tasks')).data}
async function openTask(item:any){current.value=(await api.get(`/patient-session/tasks/${item.id}`)).data;answers.value={...current.value.answers};revision.value=current.value.revision;submitted.value=false}
async function save(){if(!current.value||current.value.status==='submitted')return;saveState.value='保存中…';try{const {data}=await api.put(`/patient-session/tasks/${current.value.id}/draft`,{answers:answers.value,revision:revision.value});revision.value=data.revision;saveState.value='已自动保存'}catch(e){saveState.value='保存失败';ElMessage.error((e as Error).message)}}
watch(answers,()=>{saveState.value='有未保存修改';clearTimeout(timer);timer=window.setTimeout(save,5000)},{deep:true})
async function submit(){try{await ElMessageBox.confirm('提交后不能再修改答案，确认提交吗？','提交确认',{confirmButtonText:'确认提交',cancelButtonText:'继续检查'});await save();const {data}=await api.post(`/patient-session/tasks/${current.value.id}/submit`,{answers:answers.value,revision:revision.value},{headers:{'Idempotency-Key':createIdempotencyKey()}});submitted.value=true;current.value=null;await loadTasks();ElMessage.success('问卷提交成功')}catch(e){if((e as any)!=='cancel'&&(e as Error).message)ElMessage.error((e as Error).message)}}
function back(){current.value=null}
onMounted(()=>{if(sessionStorage.getItem('patient_token')){verified.value=true;loadTasks().catch(()=>{verified.value=false;sessionStorage.removeItem('patient_token')})}})
onBeforeUnmount(()=>clearTimeout(timer))
</script>
<template><div class="patient-page"><header class="patient-header"><div class="patient-brand"><span class="brand-mark">认</span><div><b>认知筛查问卷</b><small>移动填写端</small></div></div><span v-if="current" class="save-state">{{saveState}}</span></header>
<main class="patient-main">
<section v-if="!verified" class="verify-card"><span class="eyebrow">SECURE ACCESS</span><h1>开始填写问卷</h1><p>请输入医生提供的 6 位访问码。链接与访问码共同用于保护您的问卷信息。</p><el-input v-model="accessCode" maxlength="6" inputmode="numeric" size="large" class="code-input" placeholder="6 位访问码" @keyup.enter="verify"/><el-button type="primary" size="large" class="full" :loading="loading" :disabled="accessCode.length!==6" @click="verify">验证并进入</el-button><div class="privacy-note">本系统用于信息收集和筛查，不提供医学诊断。</div></section>
<section v-else-if="current" class="questionnaire-page"><button class="text-back" @click="back">← 返回任务列表</button><span class="eyebrow">{{current.name}}</span><h1>{{current.schema.title}}</h1><p class="notice-inline">{{current.schema.notice}}</p><form @submit.prevent><template v-for="(q,index) in visibleQuestions" :key="q.key"><h3 v-if="index===0||visibleQuestions[index-1].sectionTitle!==q.sectionTitle" class="section-title">{{q.sectionTitle}}</h3><DynamicQuestion :question="q" v-model="answers[q.key]"/></template><div class="patient-actions"><el-button size="large" @click="save">暂存</el-button><el-button type="primary" size="large" @click="submit">提交问卷</el-button></div></form></section>
<section v-else-if="packageData" class="task-home"><span class="eyebrow">QUESTIONNAIRE TASK</span><h1>{{packageData.assignment.title}}</h1><p>{{packageData.assignment.note}}</p><div class="task-meta"><span>患者编码 {{packageData.assignment.patient_code}}</span><span>负责医生 {{packageData.assignment.doctor_name}}</span></div><div class="progress-summary"><b>{{packageData.items.filter((i:any)=>i.status==='submitted'||i.status==='reviewed').length}} / {{packageData.items.length}}</b><span>已完成问卷</span></div><div class="task-list"><article v-for="item in packageData.items" :key="item.id" class="patient-task" :class="item.status"><div><span class="status-dot"></span><div><h3>{{item.name}}</h3><p>{{item.description}}</p></div></div><el-button v-if="!['submitted','reviewed'].includes(item.status)" type="primary" @click="openTask(item)">{{item.status==='draft'?'继续填写':'开始填写'}}</el-button><el-tag v-else type="success">已提交</el-tag></article></div><div v-if="packageData.items.every((i:any)=>['submitted','reviewed'].includes(i.status))" class="complete-banner">✓ 全部问卷已提交，感谢您的配合。医生将结合其他信息进行专业评估。</div></section>
</main></div></template>
