import { createServer } from "node:http";
import { randomUUID } from "node:crypto";
import { hasAssessment, scoreSubmission } from "./assessments.mjs";
import { readStore, resetStore, writeStore } from "./store.mjs";
const port = Number(process.env.PORT ?? 3001);
const send = (res, status, body) => { res.writeHead(status, { "Content-Type": "application/json; charset=utf-8" }); res.end(status === 204 ? undefined : JSON.stringify(body)); };
const fail = (res, status, code, message) => send(res, status, { error: { code, message } });
async function bodyOf(req) { const chunks = []; let length = 0; for await (const chunk of req) { length += chunk.length; if (length > 1048576) throw new Error("PAYLOAD_TOO_LARGE"); chunks.push(chunk); } return chunks.length ? JSON.parse(Buffer.concat(chunks).toString("utf8")) : {}; }
function match(pathname, pattern) { const names = []; const regex = new RegExp(`^${pattern.replace(/:([A-Za-z]+)/g, (_, name) => { names.push(name); return "([^/]+)"; })}$`); const values = pathname.match(regex); return values ? Object.fromEntries(names.map((name, index) => [name, decodeURIComponent(values[index + 1])])) : null; }

createServer(async (req, res) => {
  res.setHeader("X-Request-Id", randomUUID());
  try {
    const url = new URL(req.url, `http://${req.headers.host ?? "localhost"}`); const method = req.method ?? "GET"; let params;
    if (method === "GET" && url.pathname === "/api/health") return send(res, 200, { status: "ok" });
    const store = await readStore();
    if (method === "GET" && url.pathname === "/api/patients") return send(res, 200, store.patients);
    if (method === "GET" && url.pathname === "/api/patients/current") return send(res, 200, store.patients.find((p) => p.id === store.currentPatientId) ?? store.patients[0]);
    if (method === "PUT" && url.pathname === "/api/patients/current") { const body = await bodyOf(req); const patient = store.patients.find((p) => p.id === body.patientId); if (!patient) return fail(res, 404, "PATIENT_NOT_FOUND", "未找到患者"); store.currentPatientId = body.patientId; await writeStore(store); return send(res, 200, patient); }
    if (method === "GET" && (params = match(url.pathname, "/api/patients/:patientId/assignments"))) return send(res, 200, store.assignments.filter((a) => a.patientId === params.patientId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)));
    if (method === "POST" && url.pathname === "/api/assignments") { const body = await bodyOf(req); if (!store.patients.some((p) => p.id === body.patientId)) return fail(res, 404, "PATIENT_NOT_FOUND", "未找到患者"); if (!hasAssessment(body.assessmentId)) return fail(res, 404, "ASSESSMENT_NOT_FOUND", "未找到量表"); const assignment = { assignmentId: `assignment-${randomUUID()}`, patientId: body.patientId, assessmentId: body.assessmentId, createdAt: new Date().toISOString(), status: "pending" }; store.assignments.unshift(assignment); await writeStore(store); return send(res, 201, assignment); }
    if (method === "GET" && (params = match(url.pathname, "/api/assignments/:assignmentId/draft"))) return send(res, 200, store.drafts.find((d) => d.assignmentId === params.assignmentId) ?? null);
    if (method === "PUT" && (params = match(url.pathname, "/api/assignments/:assignmentId/draft"))) { const body = await bodyOf(req); const assignment = store.assignments.find((a) => a.assignmentId === params.assignmentId); if (!assignment) return fail(res, 404, "ASSIGNMENT_NOT_FOUND", "未找到评估任务"); if (assignment.status === "completed") return fail(res, 409, "ASSIGNMENT_NOT_EDITABLE", "任务已完成"); if (assignment.patientId !== body.patientId || assignment.assessmentId !== body.assessmentId) return fail(res, 403, "ASSIGNMENT_MISMATCH", "任务信息不匹配"); const existing = store.drafts.find((d) => d.assignmentId === params.assignmentId); const answers = existing ? [...existing.answers] : []; const index = answers.findIndex((a) => a.questionId === body.questionId); const answer = { questionId: body.questionId, value: body.value, score: 0 }; if (index >= 0) answers[index] = answer; else answers.push(answer); const draft = { assignmentId: params.assignmentId, patientId: body.patientId, assessmentId: body.assessmentId, startedAt: existing?.startedAt ?? body.startedAt, updatedAt: new Date().toISOString(), answers }; store.drafts = [draft, ...store.drafts.filter((d) => d.assignmentId !== params.assignmentId)]; assignment.status = "in_progress"; assignment.startedAt ??= body.startedAt; await writeStore(store); return send(res, 200, draft); }
    if (method === "POST" && (params = match(url.pathname, "/api/assignments/:assignmentId/submit"))) { const body = await bodyOf(req); const assignment = store.assignments.find((a) => a.assignmentId === params.assignmentId); if (!assignment) return fail(res, 404, "ASSIGNMENT_NOT_FOUND", "未找到评估任务"); const existing = store.submissions.find((s) => s.assignmentId === params.assignmentId); if (existing) return send(res, 200, existing); if (assignment.patientId !== body.patientId || assignment.assessmentId !== body.assessmentId) return fail(res, 403, "ASSIGNMENT_MISMATCH", "任务信息不匹配"); const scored = scoreSubmission(assignment.assessmentId, body.answers); const completedAt = new Date().toISOString(); const startedAt = assignment.startedAt ?? body.startedAt; const submission = { assignmentId: assignment.assignmentId, patientId: assignment.patientId, assessmentId: assignment.assessmentId, startedAt, completedAt, answers: scored.answers, result: scored.result, metrics: { durationMs: Math.max(0, Date.parse(completedAt) - Date.parse(startedAt)) } }; store.submissions.unshift(submission); store.drafts = store.drafts.filter((d) => d.assignmentId !== params.assignmentId); assignment.status = "completed"; assignment.startedAt = startedAt; assignment.completedAt = completedAt; await writeStore(store); return send(res, 201, submission); }
    if (method === "GET" && (params = match(url.pathname, "/api/assignments/:assignmentId/submission"))) return send(res, 200, store.submissions.find((s) => s.assignmentId === params.assignmentId) ?? null);
    if (method === "GET" && url.pathname === "/api/submissions") { const patientId = url.searchParams.get("patientId"); const items = patientId ? store.submissions.filter((s) => s.patientId === patientId) : store.submissions; return send(res, 200, items.sort((a, b) => b.completedAt.localeCompare(a.completedAt))); }
    if (method === "DELETE" && url.pathname === "/api/demo") { await resetStore(); return send(res, 204); }
    return fail(res, 404, "ROUTE_NOT_FOUND", "接口不存在");
  } catch (error) { const code = error instanceof Error ? error.message : "INTERNAL_ERROR"; const validation = new Set(["ANSWERS_REQUIRED", "INVALID_ANSWER", "DUPLICATE_ANSWER", "INCOMPLETE_ANSWERS", "INVALID_ANSWER_VALUE"]); return fail(res, validation.has(code) ? 400 : code === "PAYLOAD_TOO_LARGE" ? 413 : 500, code, validation.has(code) ? "回答数据不完整或格式不正确" : "服务器处理失败"); }
}).listen(port, "127.0.0.1", () => console.log(`Assessment API listening on http://127.0.0.1:${port}`));
