<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api } from '../api/client'
import { formatDateTime } from '../utils/date'

const active=ref('users');const users=ref<any[]>([]);const departments=ref<any[]>([]);const audits=ref<any[]>([]);const loading=ref(false)
const userDialog=ref(false);const editingUser=ref<any>();const departmentDialog=ref(false);const editingDepartment=ref<any>()
const permissionLabels:any={can_create_patients:'创建患者',can_assign_questionnaires:'派发与修改任务',can_review_results:'查看结果与写诊疗记录',can_manage_templates:'管理问卷模板'}
const userForm=reactive<any>({username:'',password:'',display_name:'',role:'doctor',department_id:null,active:true,permissions:{can_create_patients:true,can_assign_questionnaires:true,can_review_results:true,can_manage_templates:false}})
const departmentForm=reactive<any>({code:'',name:'',active:true})
function permissionHelp(key:string|number){return String(key)==='can_review_results'?'涉及敏感医疗记录，请按岗位授权':'关闭后相关入口仍会由后端拒绝访问'}
async function load(){loading.value=true;try{const [u,d,a]=await Promise.all([api.get('/admin/users'),api.get('/admin/departments'),api.get('/admin/audit')]);users.value=u.data;departments.value=d.data;audits.value=a.data}finally{loading.value=false}}
function openUser(row?:any){editingUser.value=row;Object.assign(userForm,row?{display_name:row.display_name,role:row.role,department_id:row.department_id,active:row.active,new_password:'',permissions:{...row.permissions}}:{username:'',password:'',display_name:'',role:'doctor',department_id:null,active:true,permissions:{can_create_patients:true,can_assign_questionnaires:true,can_review_results:true,can_manage_templates:false}});userDialog.value=true}
async function saveUser(){try{if(editingUser.value){const payload={display_name:userForm.display_name,role:userForm.role,department_id:userForm.department_id,active:userForm.active,permissions:userForm.permissions,...(userForm.new_password?{new_password:userForm.new_password}:{})};await api.patch(`/admin/users/${editingUser.value.id}`,payload)}else await api.post('/admin/users',userForm);ElMessage.success('账号与权限已保存');userDialog.value=false;load()}catch(e){ElMessage.error((e as Error).message)}}
function openDepartment(row?:any){editingDepartment.value=row;Object.assign(departmentForm,row?{code:row.code,name:row.name,active:row.active}:{code:'',name:'',active:true});departmentDialog.value=true}
async function saveDepartment(){try{editingDepartment.value?await api.patch(`/admin/departments/${editingDepartment.value.id}`,departmentForm):await api.post('/admin/departments',departmentForm);ElMessage.success('科室信息已保存');departmentDialog.value=false;load()}catch(e){ElMessage.error((e as Error).message)}}
onMounted(load)
</script>

<template><div v-loading="loading"><div class="page-heading"><div><span class="eyebrow">CONTROL PLANE</span><h1>组织与权限中心</h1><p>集中管理账号、科室、业务授权和关键操作审计。</p></div><div class="system-badge"><i></i>权限服务正常</div></div>
<div class="admin-metrics"><div><small>在岗账号</small><strong>{{users.filter(i=>i.active).length}}</strong></div><div><small>医生账号</small><strong>{{users.filter(i=>i.role==='doctor').length}}</strong></div><div><small>启用科室</small><strong>{{departments.filter(i=>i.active).length}}</strong></div><div><small>近期审计事件</small><strong>{{audits.length}}</strong></div></div>
<article class="panel admin-console"><el-tabs v-model="active">
<el-tab-pane label="账号与权限" name="users"><div class="console-toolbar"><div><h3>人员访问控制</h3><p>角色决定管理范围，权限开关决定医生可执行的具体业务。</p></div><el-button type="primary" @click="openUser()">+ 新增账号</el-button></div><el-table :data="users"><el-table-column prop="display_name" label="姓名" min-width="120"><template #default="s"><b>{{s.row.display_name}}</b><small class="table-sub">{{s.row.username}}</small></template></el-table-column><el-table-column label="角色" width="95"><template #default="s"><el-tag :type="s.row.role==='admin'?'danger':'primary'">{{s.row.role==='admin'?'管理员':'医生'}}</el-tag></template></el-table-column><el-table-column prop="department_name" label="科室" min-width="120"/><el-table-column label="业务权限" min-width="320"><template #default="s"><span v-for="(enabled,key) in s.row.permissions" :key="key" v-show="enabled" class="permission-pill">{{permissionLabels[key]}}</span></template></el-table-column><el-table-column label="状态" width="85"><template #default="s"><span :class="['state-dot',s.row.active?'on':'off']"></span>{{s.row.active?'启用':'停用'}}</template></el-table-column><el-table-column label="操作" width="90"><template #default="s"><el-button link type="primary" @click="openUser(s.row)">配置</el-button></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="科室管理" name="departments"><div class="console-toolbar"><div><h3>科室与数据域</h3><p>科室用于组织医生与患者的数据归属。</p></div><el-button type="primary" @click="openDepartment()">+ 新建科室</el-button></div><el-table :data="departments"><el-table-column prop="code" label="编码" width="120"/><el-table-column prop="name" label="科室名称"/><el-table-column label="状态" width="120"><template #default="s"><el-tag :type="s.row.active?'success':'info'">{{s.row.active?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="90"><template #default="s"><el-button link type="primary" @click="openDepartment(s.row)">编辑</el-button></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="操作审计" name="audit"><div class="console-toolbar"><div><h3>安全审计轨迹</h3><p>保留登录、查看结果、派发、权限修改与临床记录操作。</p></div></div><el-table :data="audits"><el-table-column prop="created_at" label="时间" min-width="170"><template #default="s">{{formatDateTime(s.row.created_at)}}</template></el-table-column><el-table-column prop="actor_id" label="操作者" width="100"/><el-table-column prop="action" label="动作" min-width="170"/><el-table-column label="对象" min-width="170"><template #default="s">{{s.row.target_type}} #{{s.row.target_id}}</template></el-table-column><el-table-column prop="result" label="结果" width="100"/></el-table></el-tab-pane>
</el-tabs></article>
<el-dialog v-model="userDialog" :title="editingUser?'配置账号与权限':'新增医务账号'" width="650px"><el-form label-position="top"><div class="form-grid"><el-form-item v-if="!editingUser" label="登录账号"><el-input v-model="userForm.username"/></el-form-item><el-form-item v-if="!editingUser" label="初始密码"><el-input v-model="userForm.password" type="password" show-password/></el-form-item><el-form-item label="姓名"><el-input v-model="userForm.display_name"/></el-form-item><el-form-item label="角色"><el-select v-model="userForm.role"><el-option label="医生" value="doctor"/><el-option label="管理员" value="admin"/></el-select></el-form-item><el-form-item label="所属科室"><el-select v-model="userForm.department_id" clearable><el-option v-for="d in departments" :key="d.id" :label="d.name" :value="d.id"/></el-select></el-form-item><el-form-item v-if="editingUser" label="重置密码（不修改请留空）"><el-input v-model="userForm.new_password" type="password" show-password/></el-form-item></div><el-form-item label="账号状态"><el-switch v-model="userForm.active" active-text="启用" inactive-text="停用"/></el-form-item><div class="permission-grid"><label v-for="(label,key) in permissionLabels" :key="key"><div><b>{{label}}</b><small>{{permissionHelp(key)}}</small></div><el-switch v-model="userForm.permissions[key]"/></label></div></el-form><template #footer><el-button @click="userDialog=false">取消</el-button><el-button type="primary" @click="saveUser">保存配置</el-button></template></el-dialog>
<el-dialog v-model="departmentDialog" :title="editingDepartment?'编辑科室':'新建科室'" width="460px"><el-form label-position="top"><el-form-item label="科室编码"><el-input v-model="departmentForm.code"/></el-form-item><el-form-item label="科室名称"><el-input v-model="departmentForm.name"/></el-form-item><el-form-item label="状态"><el-switch v-model="departmentForm.active" active-text="启用"/></el-form-item></el-form><template #footer><el-button @click="departmentDialog=false">取消</el-button><el-button type="primary" @click="saveDepartment">保存</el-button></template></el-dialog>
</div></template>
