<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { api } from '../api/client'
import ChartPanel from '../components/ChartPanel.vue'
import { useAuthStore } from '../stores/auth'
const route=useRoute();const auth=useAuthStore();const patient=ref<any>();const analysis=ref<any>();const records=ref<any[]>([]);const loading=ref(true);const active=ref('overview');const dialog=ref(false);const editing=ref<any>();const patientDialog=ref(false)
const riskText:any={low:'低风险',medium:'中风险',high:'高风险',unknown:'待评估'};const statusText:any={pending:'未打开',in_progress:'填写中',submitted:'已提交',reviewed:'已复核',revoked:'已撤销',expired:'已过期'};const recordText:any={diagnosis:'诊断记录',follow_up:'随访记录',treatment:'处置方案',note:'临床备注'}
const form=reactive<any>({record_type:'follow_up',title:'',diagnosis_code:'',content:'',event_at:''})
const patientForm=reactive<any>({full_name:'',sex:'',birth_date:'',phone:'',education_level:'',residence_type:'',marital_status:'',occupation:'',chief_concern:'',past_medical_history:'',family_history:'',current_medications:'',allergy_history:'',emergency_contact:'',emergency_phone:''})
const canReview=computed(()=>auth.user?.role==='admin'||auth.user?.permissions?.can_review_results)
const canEditPatient=computed(()=>auth.user?.role==='admin'||auth.user?.permissions?.can_create_patients)
const trendOption=computed(()=>({tooltip:{trigger:'axis'},grid:{left:50,right:24,top:42,bottom:48},xAxis:{type:'category',name:'评估日期',nameTextStyle:{color:'#8a9ab0'},data:(analysis.value?.trend||[]).map((i:any)=>new Date(i.assessed_at).toLocaleDateString()),axisLabel:{color:'#7f91ad'}},yAxis:{type:'value',name:'得分',min:0,axisLabel:{color:'#7f91ad'},splitLine:{lineStyle:{color:'rgba(111,137,173,.14)'}}},series:[{name:'问卷得分',type:'line',smooth:true,showSymbol:true,symbol:'circle',symbolSize:12,data:(analysis.value?.trend||[]).map((i:any)=>i.total_score),label:{show:true,formatter:'{c} 分',position:'top',color:'#1686d9',fontWeight:700},lineStyle:{width:3,color:'#49d9f3'},itemStyle:{color:'#1686d9',borderColor:'#fff',borderWidth:3},areaStyle:{color:'rgba(73,217,243,.12)'}}]}))
async function load(){loading.value=true;try{const id=route.params.id;const calls=[api.get(`/patients/${id}`),api.get(`/patients/${id}/analysis`)];if(canReview.value)calls.push(api.get(`/patients/${id}/clinical-records`));const data=await Promise.all(calls);patient.value=data[0].data;analysis.value=data[1].data;records.value=data[2]?.data||[]}finally{loading.value=false}}
function openRecord(row?:any){editing.value=row;Object.assign(form,row?{record_type:row.record_type,title:row.title,diagnosis_code:row.diagnosis_code||'',content:row.content,event_at:row.event_at}:{record_type:'follow_up',title:'',diagnosis_code:'',content:'',event_at:new Date().toISOString()});dialog.value=true}
async function saveRecord(){try{const payload={...form,diagnosis_code:form.diagnosis_code||null,event_at:form.event_at||null,...(editing.value?{status:editing.value.status}:{})};editing.value?await api.patch(`/patients/${patient.value.id}/clinical-records/${editing.value.id}`,payload):await api.post(`/patients/${patient.value.id}/clinical-records`,payload);ElMessage.success('临床记录已安全保存');dialog.value=false;load()}catch(e){ElMessage.error((e as Error).message)}}
function openPatientEdit(){for(const key of Object.keys(patientForm))patientForm[key]=patient.value[key]||'';patientDialog.value=true}
async function savePatient(){try{const payload=Object.fromEntries(Object.entries(patientForm).map(([key,value])=>[key,value||null]));await api.patch(`/patients/${patient.value.id}`,payload);ElMessage.success('患者信息已更新');patientDialog.value=false;await load()}catch(e){ElMessage.error((e as Error).message)}}
onMounted(load)
</script>
<template><div v-loading="loading"><template v-if="patient&&analysis"><div class="patient-hero"><div><div class="patient-idline"><span class="patient-avatar">{{patient.full_name?.slice(0,1)||patient.patient_code.slice(-2)}}</span><div><span class="eyebrow">LONGITUDINAL PATIENT RECORD</span><h1>{{patient.full_name||'姓名待补充'}}</h1><p>档案号 {{patient.patient_code}} · {{patient.department_name}} · 主诊医生 {{patient.doctor_name}} · {{analysis.age??'年龄未知'}} 岁</p></div></div></div><div class="hero-actions"><div :class="['risk-orbit',analysis.latest_risk]"><i></i><span>当前提示</span><b>{{riskText[analysis.latest_risk]}}</b></div><router-link v-if="auth.user?.role==='admin'||auth.user?.permissions?.can_assign_questionnaires" :to="`/assignments/create?patient=${patient.id}`"><el-button type="primary" size="large">+ 派发评估</el-button></router-link></div></div>
<div class="patient-kpis"><div><small>累计评估</small><strong>{{analysis.assessment_count}}</strong><span>次已提交问卷</span></div><div><small>任务完成率</small><strong>{{analysis.completion_rate}}%</strong><span>{{analysis.assignment_count}} 个任务</span></div><div><small>高风险提示</small><strong>{{analysis.risk_counts.high}}</strong><span>仅供临床复核</span></div><div><small>最近记录</small><strong>{{records.length}}</strong><span>诊断 / 随访 / 处置</span></div></div>
<article class="patient-workspace"><el-tabs v-model="active"><el-tab-pane label="临床概览" name="overview"><div class="clinical-grid"><article class="panel profile-panel"><div class="panel-head"><h3>患者基本信息</h3><div class="profile-title-actions"><span class="data-source">PATIENT MASTER</span><el-button v-if="canEditPatient" link type="primary" @click="openPatientEdit">编辑资料</el-button></div></div><dl class="detail-list"><dt>姓名</dt><dd>{{patient.full_name||'待补充'}}</dd><dt>性别</dt><dd>{{patient.sex==='male'?'男':patient.sex==='female'?'女':patient.sex==='other'?'其他':'未填写'}}</dd><dt>年龄</dt><dd>{{patient.age!=null?`${patient.age} 岁`:'未填写出生日期'}}</dd><dt>出生日期</dt><dd>{{patient.birth_date||'未填写'}}</dd><dt>联系电话</dt><dd>{{patient.phone||'未填写'}}</dd><dt>婚姻状况</dt><dd>{{patient.marital_status||'未填写'}}</dd><dt>职业</dt><dd>{{patient.occupation||'未填写'}}</dd><dt>教育程度</dt><dd>{{patient.education_level||'未填写'}}</dd><dt>居住类型</dt><dd>{{patient.residence_type||'未填写'}}</dd><dt>紧急联系人</dt><dd>{{patient.emergency_contact||'未填写'}} {{patient.emergency_phone||''}}</dd></dl></article><article class="panel latest-scale"><div class="panel-head"><h3>最新量表快照</h3><span class="data-source">AUTO SCORED</span></div><el-empty v-if="!analysis.latest_by_scale.length" description="尚无已提交评估"/><div v-for="a in analysis.latest_by_scale" :key="a.id" class="scale-snapshot"><div><b>{{a.questionnaire_code}}</b><span>{{new Date(a.assessed_at).toLocaleString()}}</span></div><strong>{{a.total_score??'—'}}<small>分</small></strong><el-tag :type="a.risk_level==='high'?'danger':a.risk_level==='medium'?'warning':'success'">{{riskText[a.risk_level]}}</el-tag></div></article></div><article class="panel medical-profile"><div class="panel-head"><h3>医学与照护信息</h3><span class="data-source">CLINICAL PROFILE</span></div><div class="medical-grid"><div><small>主要症状 / 就诊原因</small><p>{{patient.chief_concern||'未填写'}}</p></div><div><small>既往病史</small><p>{{patient.past_medical_history||'未填写'}}</p></div><div><small>家族史</small><p>{{patient.family_history||'未填写'}}</p></div><div><small>当前用药</small><p>{{patient.current_medications||'未填写'}}</p></div><div><small>过敏史</small><p>{{patient.allergy_history||'未填写'}}</p></div></div></article><div class="notice-card clinical-note"><b>临床边界</b><p>自动评分只形成风险提示；医生记录为人工录入，正式诊断需结合面诊及规范检查。</p></div></el-tab-pane>
<el-tab-pane label="趋势分析" name="analysis"><div v-if="analysis.assessment_count<2" class="trend-guidance"><b>{{analysis.assessment_count===0?'尚无评估数据':'当前只有 1 次评估'}}</b><span>{{analysis.assessment_count===0?'患者提交问卷后将在此显示得分。':'已显示本次得分点；至少完成 2 次同类评估后，才能判断上升或下降趋势。'}}</span></div><div class="trend-layout"><ChartPanel title="纵向评估得分趋势" :option="trendOption"/><article class="panel"><div class="panel-head"><h3>风险事件分布</h3><span class="data-source">{{analysis.assessment_count}} 次评估</span></div><div class="risk-stack"><div v-for="level in ['high','medium','low','unknown']" :key="level"><span>{{riskText[level]}}</span><i><em :class="level" :style="{width:`${analysis.assessment_count?analysis.risk_counts[level]*100/analysis.assessment_count:0}%`}"></em></i><b>{{analysis.risk_counts[level]}}</b></div></div></article></div><article class="panel table-panel"><el-table :data="[...analysis.trend].reverse()"><el-table-column prop="questionnaire_code" label="问卷"/><el-table-column prop="assessed_at" label="评估时间"><template #default="s">{{new Date(s.row.assessed_at).toLocaleString()}}</template></el-table-column><el-table-column prop="total_score" label="总分" width="100"/><el-table-column label="风险" width="110"><template #default="s"><el-tag :type="s.row.risk_level==='high'?'danger':s.row.risk_level==='medium'?'warning':'success'">{{riskText[s.row.risk_level]}}</el-tag></template></el-table-column><el-table-column prop="review_status" label="复核状态" width="120"/></el-table></article></el-tab-pane>
<el-tab-pane label="诊疗记录" name="records"><div class="console-toolbar"><div><h3>医生诊断与随访时间线</h3><p>每条记录保留作者、发生时间和修改时间，可供连续诊疗追溯。</p></div><el-button v-if="canReview" type="primary" @click="openRecord()">+ 新增临床记录</el-button></div><el-empty v-if="!canReview" description="当前账号未获得临床记录权限"/><div v-else class="clinical-timeline"><article v-for="row in records" :key="row.id" :class="['record-card',row.record_type]"><div class="record-rail"><i></i></div><div class="record-main"><div class="record-meta"><el-tag>{{recordText[row.record_type]}}</el-tag><span>{{new Date(row.event_at).toLocaleString()}}</span><span>{{row.doctor_name}}</span></div><div class="record-title"><h3>{{row.title}}</h3><el-button link type="primary" @click="openRecord(row)">编辑</el-button></div><code v-if="row.diagnosis_code">诊断编码 {{row.diagnosis_code}}</code><p>{{row.content}}</p><small>最后更新 {{new Date(row.updated_at).toLocaleString()}}</small></div></article></div></el-tab-pane>
<el-tab-pane label="任务历史" name="tasks"><article class="panel table-panel"><el-table :data="analysis.assignments"><el-table-column prop="title" label="任务" min-width="180"/><el-table-column prop="doctor_name" label="负责医生"/><el-table-column label="创建时间"><template #default="s">{{new Date(s.row.created_at).toLocaleString()}}</template></el-table-column><el-table-column label="截止时间"><template #default="s">{{s.row.deadline?new Date(s.row.deadline).toLocaleString():'不限时'}}</template></el-table-column><el-table-column label="状态" width="110"><template #default="s"><el-tag>{{statusText[s.row.status]||s.row.status}}</el-tag></template></el-table-column></el-table></article></el-tab-pane></el-tabs></article>
<el-dialog v-model="dialog" :title="editing?'编辑临床记录':'新增临床记录'" width="680px"><el-form label-position="top"><div class="form-grid"><el-form-item label="记录类型"><el-select v-model="form.record_type"><el-option v-for="(label,key) in recordText" :key="key" :label="label" :value="key"/></el-select></el-form-item><el-form-item label="发生时间"><el-date-picker v-model="form.event_at" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" class="full"/></el-form-item></div><el-form-item label="标题"><el-input v-model="form.title"/></el-form-item><el-form-item v-if="form.record_type==='diagnosis'" label="诊断编码（可选）"><el-input v-model="form.diagnosis_code" placeholder="例如 ICD-10 编码；演示环境请勿录入真实身份信息"/></el-form-item><el-form-item label="记录内容"><el-input v-model="form.content" type="textarea" :rows="7" placeholder="记录症状变化、临床判断、处置与随访计划"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :disabled="!form.title||!form.content" @click="saveRecord">保存记录</el-button></template></el-dialog>
<el-dialog v-model="patientDialog" title="填写患者完整档案" width="min(780px,94vw)" top="5vh"><el-form label-position="top"><div class="record-section-title">基本信息</div><div class="form-grid"><el-form-item label="患者姓名（必填）"><el-input v-model="patientForm.full_name"/></el-form-item><el-form-item label="性别"><el-select v-model="patientForm.sex" clearable class="full"><el-option label="男" value="male"/><el-option label="女" value="female"/><el-option label="其他" value="other"/></el-select></el-form-item><el-form-item label="出生日期（自动计算年龄）"><el-date-picker v-model="patientForm.birth_date" value-format="YYYY-MM-DD" clearable class="full"/></el-form-item><el-form-item label="联系电话"><el-input v-model="patientForm.phone"/></el-form-item><el-form-item label="婚姻状况"><el-input v-model="patientForm.marital_status"/></el-form-item><el-form-item label="职业"><el-input v-model="patientForm.occupation"/></el-form-item><el-form-item label="教育程度"><el-input v-model="patientForm.education_level"/></el-form-item><el-form-item label="居住类型"><el-input v-model="patientForm.residence_type"/></el-form-item><el-form-item label="紧急联系人"><el-input v-model="patientForm.emergency_contact"/></el-form-item><el-form-item label="紧急联系电话"><el-input v-model="patientForm.emergency_phone"/></el-form-item></div><div class="record-section-title">医学与照护信息</div><el-form-item label="主要症状 / 就诊原因"><el-input v-model="patientForm.chief_concern" type="textarea" :rows="2"/></el-form-item><div class="form-grid"><el-form-item label="既往病史"><el-input v-model="patientForm.past_medical_history" type="textarea" :rows="3"/></el-form-item><el-form-item label="家族史"><el-input v-model="patientForm.family_history" type="textarea" :rows="3"/></el-form-item><el-form-item label="当前用药"><el-input v-model="patientForm.current_medications" type="textarea" :rows="3"/></el-form-item><el-form-item label="过敏史"><el-input v-model="patientForm.allergy_history" type="textarea" :rows="3"/></el-form-item></div></el-form><template #footer><el-button @click="patientDialog=false">取消</el-button><el-button type="primary" :disabled="!patientForm.full_name" @click="savePatient">保存患者信息</el-button></template></el-dialog>
</template></div></template>

<style scoped>
.profile-title-actions { display: flex; align-items: center; gap: 12px; }
.record-section-title { font-weight: 700; color: #18304f; border-left: 3px solid #26b9de; padding-left: 9px; margin: 4px 0 16px; }
.medical-profile { margin-top: 16px; }
.medical-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; }
.medical-grid > div { background: #f6f9fd; border: 1px solid #e5edf6; border-radius: 10px; padding: 13px 15px; }
.medical-grid small { color: #71819a; }
.medical-grid p { margin: 7px 0 0; color: #253955; line-height: 1.6; white-space: pre-wrap; }
.trend-guidance { display: flex; gap: 12px; align-items: center; background: #eef8fc; border: 1px solid #d8edf5; color: #365b73; padding: 12px 16px; border-radius: 10px; margin-bottom: 14px; }
.trend-guidance span { font-size: 12px; }
@media (max-width: 700px) { .medical-grid { grid-template-columns: 1fr; } }
</style>
