<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api/client'
import { useAuthStore } from '../stores/auth'

const auth = useAuthStore()
const patients = ref<any[]>([])
const total = ref(0)
const keyword = ref('')
const loading = ref(false)
const dialog = ref(false)
const emptyForm = () => ({patient_code:'',full_name:'',sex:'',birth_date:'',phone:'',education_level:'',residence_type:'',marital_status:'',occupation:'',chief_concern:'',past_medical_history:'',family_history:'',current_medications:'',allergy_history:'',emergency_contact:'',emergency_phone:''})
const form = reactive<any>(emptyForm())

async function load(){loading.value=true;try{const {data}=await api.get('/patients',{params:{keyword:keyword.value}});patients.value=data.items;total.value=data.total}finally{loading.value=false}}
async function create(){try{const payload=Object.fromEntries(Object.entries(form).map(([key,value])=>[key,value||null]));payload.patient_code=form.patient_code;payload.full_name=form.full_name;await api.post('/patients',payload);ElMessage.success('患者档案创建成功');dialog.value=false;Object.assign(form,emptyForm());load()}catch(e){ElMessage.error((e as Error).message)}}
async function archive(row:any){try{await ElMessageBox.confirm(`确认归档患者“${row.full_name||row.patient_code}”吗？未完成任务将同时撤销，历史记录仍会保留。`,'管理员归档确认',{type:'warning',confirmButtonText:'确认归档',cancelButtonText:'取消'});await api.delete(`/patients/${row.id}`);ElMessage.success('患者已归档');load()}catch(e){if(e!=='cancel'&&(e as Error).message)ElMessage.error((e as Error).message)}}
onMounted(load)
</script>

<template><div><div class="page-heading"><div><span class="eyebrow">PATIENT CENTER</span><h1>患者管理</h1><p>管理患者主档、医学信息、筛查任务与连续诊疗记录。</p></div><el-button type="primary" @click="dialog=true">+ 新建患者</el-button></div><article class="panel table-panel"><div class="toolbar"><el-input v-model="keyword" placeholder="搜索患者姓名或编码" clearable @keyup.enter="load"/><el-button @click="load">查询</el-button><span class="muted">共 {{total}} 人</span></div><el-table :data="patients" v-loading="loading"><el-table-column prop="full_name" label="患者姓名" min-width="120"><template #default="s"><router-link class="table-link" :to="`/patients/${s.row.id}`">{{s.row.full_name||'待补充'}}</router-link><small class="table-sub">{{s.row.patient_code}}</small></template></el-table-column><el-table-column prop="sex" label="性别" width="75"><template #default="s">{{s.row.sex==='male'?'男':s.row.sex==='female'?'女':s.row.sex==='other'?'其他':'—'}}</template></el-table-column><el-table-column prop="age" label="年龄" width="75"><template #default="s">{{s.row.age??'—'}}</template></el-table-column><el-table-column prop="phone" label="联系电话" min-width="125"><template #default="s">{{s.row.phone||'—'}}</template></el-table-column><el-table-column prop="department_name" label="科室" min-width="110"/><el-table-column prop="doctor_name" label="主诊医生" min-width="100"/><el-table-column label="操作" width="190" fixed="right"><template #default="s"><router-link :to="`/assignments/create?patient=${s.row.id}`"><el-button link type="primary">派发问卷</el-button></router-link><el-button v-if="auth.user?.role==='admin'" link type="danger" @click="archive(s.row)">归档患者</el-button></template></el-table-column></el-table></article>
<el-dialog v-model="dialog" title="建立患者档案" width="min(780px,94vw)" top="5vh"><el-form label-position="top"><div class="record-section-title">基本信息</div><div class="form-grid"><el-form-item label="患者姓名（必填）"><el-input v-model="form.full_name" placeholder="请输入姓名"/></el-form-item><el-form-item label="患者编码（必填）"><el-input v-model="form.patient_code" placeholder="例如 P0101"/></el-form-item><el-form-item label="性别"><el-select v-model="form.sex" clearable class="full"><el-option label="男" value="male"/><el-option label="女" value="female"/><el-option label="其他" value="other"/></el-select></el-form-item><el-form-item label="出生日期（自动计算年龄）"><el-date-picker v-model="form.birth_date" value-format="YYYY-MM-DD" class="full"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.phone"/></el-form-item><el-form-item label="婚姻状况"><el-input v-model="form.marital_status"/></el-form-item><el-form-item label="教育程度"><el-input v-model="form.education_level"/></el-form-item><el-form-item label="职业"><el-input v-model="form.occupation"/></el-form-item><el-form-item label="居住类型"><el-input v-model="form.residence_type"/></el-form-item></div><div class="record-section-title">医学与照护信息</div><el-form-item label="主要症状 / 就诊原因"><el-input v-model="form.chief_concern" type="textarea" :rows="2"/></el-form-item><div class="form-grid"><el-form-item label="既往病史"><el-input v-model="form.past_medical_history" type="textarea" :rows="3" placeholder="高血压、糖尿病、脑卒中、手术史等"/></el-form-item><el-form-item label="家族史"><el-input v-model="form.family_history" type="textarea" :rows="3"/></el-form-item><el-form-item label="当前用药"><el-input v-model="form.current_medications" type="textarea" :rows="3"/></el-form-item><el-form-item label="过敏史"><el-input v-model="form.allergy_history" type="textarea" :rows="3"/></el-form-item><el-form-item label="紧急联系人"><el-input v-model="form.emergency_contact"/></el-form-item><el-form-item label="紧急联系电话"><el-input v-model="form.emergency_phone"/></el-form-item></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :disabled="!form.patient_code||!form.full_name" @click="create">保存患者档案</el-button></template></el-dialog></div></template>

<style scoped>.record-section-title{font-weight:700;color:#18304f;border-left:3px solid #26b9de;padding-left:9px;margin:4px 0 16px}</style>
